title: Gia Eacono Gillis # your name (or website title) here
logo: "/images/gia.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist / Data Analyst with Python
  <br><br>
  MBA
  <br><br>
  <a href="https://www.linkedin.com/in/giaeaconogillis/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-150192956-1 # your Google Analytics tracking ID 
