title: Gia Eacono Gillis # your name (or website title) here
logo: "/images/gia small.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Data Scientist / Data Analyst</b>
  <br><br>
  Python
  <br>
  SQL
  <br>
  Tableau
  <br>
  Big Data
  <br><br>
  <a href="https://www.linkedin.com/in/giaeaconogillis/"><img src="/images/linkedin image.png" alt="Flowers in Chania">

  
theme: jekyll-theme-minimal
google_analytics: UA-150192956-1 # your Google Analytics tracking ID 
